server:
  port: 3000

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:90902}
    topic:
      test: test
    consumer:
      group-id: order-group
      auto-offset-reset: latest

  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://localhost:27017}

logging:
  level:
    org:
      apache:
        kafka: OFF